[package]
name = "cs397_ray_tracing_sp22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
image = "0.23.14"
rand = "0.8.4"
tobj = "3.2.0"
